---
title: "Self Evaluation L01 Review"
subtitle: |
  | Data Science 3 with R 
  | STAT 301-3
author: "Lillian Valk"
pagetitle: "Self Evaluation L01 Review Lillian Valk"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false
  error: true

from: markdown+emoji
reference-location: margin
citation-location: margin 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Lillian's Repo Link](https://github.com/stat301-3-2026-spring/l01-review-lillianvalk.git)

:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

 - data cleaning/simple EDA
 - initial setup: data splitting/folding
 - create baseline recipe
 - fit models to resamples with baseline recipe
 - tune hyperparameters
 - analyze baseline results
 - feature engineer recipes using EDA
 - fit models to resamples with feature engineered recipe
 - select best model
 - fit best model to training data
 - compare prediction results to test data to assess model performance

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning tries to have some sort of outcome that is predicted or classified using data. Unsupervised learning, on the other hand, tries to simply identify patterns in data.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models aim to visually describe an aspect of the data.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models attempt to test hypotheses in order to answer research questions about the relationships between variables.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive models try to create accurate predictions for unknown data using existing data.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model relies on existing equations and assumes the data follows that equation.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

An empirically driven model does not make assumptions about the data in its predictions.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Parametric models are mechanistic and nonparametric models are empirically driven.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are easier to interpret because their form is already known as it uses an existing equation.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are less flexible as they rely on existing equation structures, while empirically driven models have more flexibility because they can base their predictions on the data itself.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Bias-variance trade-off refers to how models can tend to be overfitted or underfitted. An overfitted model is a model that is too closely trained to the training data (i.e. is too biased), so it does not make good predictions on unseen test data, which empirically driven models can fall prey to. An underfitted model is a model that is too simple and does not fully understand the complexities of the data (i.e. has too much variance), so it does not make good predictions on the training or testing data, which can happen to mechanistic models.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression problems try to predict a numerical value, such as using existing weather data to predict how many inches it will rain tomorrow. Classification problems try to predict a categorical value, such as using existing weather data to predict whether it will rain tomorrow or not.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome variable keeps the predictions generalizable because it ensures each split does not omit data points if the outcome variable is skewed.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation with repeats is used to estimate the test RMSE by separating the training data set into smaller training and testing sets and then averaging the results to estimate RMSE. The size and number of the smaller training and testing sets are dependent on the number of folds, as 3 folds will take 3 equal groups from the training set and use each of the 3 groups as a testing set one time, resulting in 3 models averaged for the RMSE. Repeats then determine how many times this process is repeated with randomized data points from the training set. In the example of 3 folds, 5 repeats will result in 15 total models averaged for the RMSE.

We use this strategy because by averaging the results from the simulated models, we can trust that our RMSEs are not due to randomness and are more reliable.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrapping is better suited for smaller datasets because it uses some datapoints from the training set multiple times.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is the process of testing a range of hyperparameters for specific models to determine what the best hyperparameters for that model are. We use this strategy because it is not immediately obvious what the best hyperparameters for a specific model and dataset are, so, by testing a range, we can see if certain hyperparameter values result in better assessment metric values than others. This then leads to hyperparameter refinement.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE and MAE.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy and ROC_AUC.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is an inferential problem because it tries to identify a relationship between two specific variables: the number of service calls and the likelihood of a customer dropping the service.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is a prediction problem because it tries to predict the likelihood of a customer dropping the company in the future.

:::

### Self Evaluation

::: {.callout-important icon="false"}

## Score 


## Explanation

Explain the score. Clearly identify what your misunderstandings were. Explain why you believe this error/misunderstanding occurred.

## Updated solution

*Only required if a 3 or less is scored on the question.*


:::
